pi-apps fork for switch
first commit with a few additions

diff --git a/apps/Windows 10 Theme/install b/apps/Windows 10 Theme/install
--- a/apps/Windows 10 Theme/install
+++ b/apps/Windows 10 Theme/install
@@ -11,7 +11,7 @@ function error {
 "${DIRECTORY}/pkg-install" "xcompmgr tint2 gtk2-engines-murrine" "$(dirname "$0")" || exit 1
 
 if [ ! -d ~/Windows-10 ];then 
-  git clone https://github.com/Botspot/Windows-10 || error "failed to download github repository!"
+  git clone https://github.com/theofficialgman/Windows-10 || error "failed to download github repository!"
 fi
 
 if [ ! -f ~/Windows-10/install ];then
